### ISSUE TITLE
Login Currently broken

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [arduino/forum-issues#159]
Login appears to be broken at the moment

A blank page is displayed after login, after redirection to this URL

https://id.arduino.cc/auth/login/?go=1%26returnurl%3Dhttp%3A%2F%2Fforum.arduino.cc%2F

Attempting to go to the url of the forum causes redirection back to this page again

So the forum is not accessible if you are logged in

Tested under the latest Firefox and also under Chrome

**Comment by trter10** [comment]
can confirm same issue

**Comment by matteosuppo** [comment]
I believe this was fixed. Can you confirm?

**Comment by sirius631** [comment]
The issue still exists in IE11.

You login and are presented with just a blank screen.
Pull up a fresh window with the Arduino environment and you'll see your user icon sitting staring at you, as you are already logged on.
Click onto 'Forum' and it will want you to login again.
Login again for the forum and it will tell you that you are already logged and will send you back to you user profile dialogue.

I got sick of it and pulled up Chrome instead. From what people are saying, it is the only browser in which the Arduino site is working properly, that is if you want to login at all. Otherwise, just don't login.
