### ISSUE TITLE
Deleting a post, which has been reported to moderator, give a PHP error

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#191]
I attempted to delete a single post, which had been reported to moderators:

http://forum.arduino.cc/index.php?action=deletemsg;topic=339965.0;msg=2345326

This page appeared after I clicked on "Remove message":

> Fatal error: Call to undefined function recountOpenReports() in /var/www/forum/Sources/RemoveTopic.php on line 1007

It appears that the function recountOpenReports is being called when you remove a message, and this does not exist.

**Comment by RobTillaart** [comment]
This happened to me some times, I always thought it is some race condition
when multiple moderators are deleting spam at the same time. Or when a job
is deleted from the recycle bin (some crap is not even worth a good recycle
bin ;),

Was the message removed from the forum?
If so, task accomplished

**Comment by nickgammon** [comment]
I think the message was deleted, but since this has happened twice now, and I already reported it once before directly to Luca, now I am raising a bug report.

**Comment by matteosuppo** [comment]
Its should be fixed now in http://forumdev.arduino.cc/

**Comment by nickgammon** [comment]
Still happening in production a moment ago:

     Fatal error: Call to undefined function recountOpenReports() in /var/www/forum/Sources/RemoveTopic.php on line 1007

**Comment by per1234** [comment]
Hi nickgammon. Thanks so much for reporting this bug. Since the forum system has been completely changed by the switch to Discourse this week, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here and I'll reopen the issue.
