### ISSUE TITLE
unsubscribe erratic

### ISSUE THREAD

**Issue by dougp2** [arduino/forum-issues#256]
Sometimes the unsubscribe link in email replies doesn't work, it takes one to the forum page.  Other times it will go to the thread and work correctly.
http://forum.arduino.cc/index.php?topic=510170.0

**Comment by dougp2** [comment]
I'm not 100% sure but, it looks like the issue has been addressed.

**Comment by per1234** [comment]
I still experience this issue regularly. It doesn't happen every time I unsubscribe, maybe 1/3 of the time.

**Comment by Serjlee** [comment]
This should actually be fixed now.

 Feel free to re-open this issue if you are still experiencing it.

**Comment by dougp2** [comment]
How to reopen?  Can't paste link.

**Comment by per1234** [comment]
@dougp2 has the issue happened again for you since it was reported fixed? It has happened to me several times since.

**Comment by dougp2** [comment]
Yes, it has reoccurred.  That's why I'm replying to the thread.  I don't know if that constitutes re-opening.

**Comment by per1234** [comment]
Since you weren't the one to close the issue, I think only someone with administrative privileges in this repository can reopen it.

**Comment by dougp2** [comment]
I dunno.   I just posted hoping the right person would see it.

**Comment by Serjlee** [comment]
In those cases you can always open a new issue referencing the old one

@dougp2 / @per1234  can you send me the unsubscribe link which didn't work? [Via PM is fine](http://forum.arduino.cc/index.php?action=profile;u=631859)

**Comment by per1234** [comment]
@Serjlee here are two unsubscribe attempts that have failed for me in the last 7 hours:
http://forum.arduino.cc/index.php?action=notifytopic;topic=537966;email;mode=1
When I clicked that link it took me to the forum home page with this URL:
https://forum.arduino.cc/?code=KClqkULnrMwsx7mMukPErYgw15I7Iv4-5zQWlNLFjuU.j29lNUYSdlUSpmulSDjpLXKf7dsxSJe6V0L33BcE090&scope=profile%3Acore%20profile%3Apublic%20profile%3Acontact%20offline&state=106977515
instead of the thread page, as happens when the unsubscribe is successful. Even though I had clicked the unsubscribe link, I received an email for the next reply to that thread.

Same with this one:
http://forum.arduino.cc/index.php?action=notifytopic;topic=537750;email;mode=1
When I clicked that link it took me to the forum home page with this URL:
https://forum.arduino.cc/?code=8eG5vROYeN01j9l_LTTNJkD42G1duogUSj5Pybi7gkU.0DFV6JeGLZoIZhI-mKHMDp9s_zzU2ezZAF1alzHcauA&scope=profile%3Acore%20profile%3Apublic%20profile%3Acontact%20offline&state=1711378701

Over the same time period, I unsubscribed from 30 other threads where the unsubscribe link to me to the thread page and I have not received any additional emails regarding any of those threads since unsubscribing.

**Comment by Serjlee** [comment]
Thanks per1234, that's useful info. Looks like the login process failed at the last step (the final redirect to the indented location), I'll take some time to debug it.

**Comment by dougp2** [comment]
per1234 links.  I tried to post links but github, or my own ineptitude, stymied me.  Thanks.

**Comment by sterretjeToo** [comment]
After the complete rework of the forum in 2021, is this still a valid issue?

**Comment by per1234** [comment]
I made extensive use of the unsubscribe via email notification link feature over the last few days and it worked 100% reliably for me so I am closing this as resolved.
